# Default
[buildPlans.iosevka-rs]
family = "Iosevka RS"
spacing = "normal"
serifs = "sans"
no-cv-ss = false

  [buildPlans.iosevka-rs.variants]
  inherits = "ss04"

  [buildPlans.iosevka-rs.ligations]
  inherits = "dlig"

[buildPlans.iosevka-rs.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rs-slab]
family = "Iosevka RS Slab"
spacing = "normal"
serifs = "slab"
no-cv-ss = false

  [buildPlans.iosevka-rs-slab.variants]
  inherits = "ss04"

  [buildPlans.iosevka-rs-slab.ligations]
  inherits = "dlig"

[buildPlans.iosevka-rs-slab.widths.normal]
shape = 600
menu = 5
css = "normal"

# Terminal
[buildPlans.iosevka-rs-terminal]
family = "Iosevka RS Terminal"
spacing = "term"
serifs = "sans"
no-cv-ss = false
no-ligation = true

  [buildPlans.iosevka-rs-terminal.variants]
  inherits = "ss04"

[buildPlans.iosevka-rs-terminal.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rs-terminal-slab]
family = "Iosevka RS Terminal Slab"
spacing = "term"
serifs = "slab"
no-cv-ss = false
no-ligation = true

  [buildPlans.iosevka-rs-terminal-slab.variants]
  inherits = "ss04"

[buildPlans.iosevka-rs-terminal-slab.widths.normal]
shape = 600
menu = 5
css = "normal"

# Quasi-proportional
[buildPlans.iosevka-rs-qp]
family = "Iosevka RS QP"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = false

  [buildPlans.iosevka-rs-qp.variants]
  inherits = "ss04"

  [buildPlans.iosevka-rs-qp.ligations]
  inherits = "dlig"

[buildPlans.iosevka-rs-qp.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-rs-qp-slab]
family = "Iosevka RS QP Slab"
spacing = "quasi-proportional"
serifs = "slab"
no-cv-ss = false

  [buildPlans.iosevka-rs-qp-slab.variants]
  inherits = "ss04"

  [buildPlans.iosevka-rs-qp-slab.ligations]
  inherits = "dlig"

[buildPlans.iosevka-rs-qp-slab.widths.normal]
shape = 600
menu = 5
css = "normal"

#Final collection
[collectPlans.iosevka-rs-all]
from = ["iosevka-rs", "iosevka-rs-slab", "iosevka-rs-terminal", "iosevka-rs-terminal-slab", "iosevka-rs-qp", "iosevka-rs-qp-slab"]
