# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Fonts

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Iosevka commit to use'     
        required: true
        type: string
      desc:
        description: 'Description of release'     
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [iosevka-rs, iosevka-rs-slab, iosevka-rs-terminal, iosevka-rs-terminal-slab, iosevka-rs-qp, iosevka-rs-qp-slab]
    steps:
    - uses: actions/checkout@v3
      with:
        repository: be5invis/Iosevka
        ref: ${{github.event.inputs.commit}}
    - uses: actions/checkout@v2
      with:
        path: rs-build
    - run: cp rs-build/private-build-plans.toml private-build-plans.toml
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: npm install ttfautohint
    - run: npm install
    - run: npm run build -- contents::${{matrix.name}}
    - run: |
        cd dist
        zip -r ${{matrix.name}} ${{matrix.name}}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 1.0
        name: Release
        body: ${{github.event.inputs.desc}}
        files: |
          dist/*.zip
  build-ttc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: be5invis/Iosevka
        ref: ${{github.event.inputs.commit}}
    - uses: actions/checkout@v2
      with:
        path: rs-build
    - run: cp rs-build/private-build-plans.toml private-build-plans.toml
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: npm install ttfautohint
    - run: npm install
    - run: npm run build -- super-ttc::iosevka-rs-all
    - run: |
        cd dist/.super-ttc
        zip -r iosevka-rs-all iosevka-rs-all
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 1.0
        name: Release
        body: ${{github.event.inputs.desc}}
        files: |
          dist/.super-ttc/*.zip
