# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Fonts

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Iosevka commit to use'     
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        name: [iosevka-rs, iosevka-rs-slab, iosevka-rs-terminal, iosevka-rs-terminal-slab]
    
    steps:
    - uses: actions/checkout@v3
      with:
        repository: be5invis/Iosevka
        ref: ${{github.event.inputs.commit}}
    - uses: actions/checkout@v2
      with:
        path: rs-build
    - run: cp rs-build/private-build-plans.toml private-build-plans.toml
    - name: Use Node.js latest
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: npm install ttfautohint
    - run: npm install
    - run: npm run build -- contents::${{matrix.name}}
    - run: zip dist/${{matrix.name}} dist/${{matrix.name}}
    - uses: actions/upload-artifact@v3.0.0
      with:
        path: dist/${{matrix.name}}.zip
